apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/mongodb

# Example: Override resources for production
# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
#         value: "20Gi"
#     target:
#       kind: StatefulSet
#       name: mongodb
