apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/kafka

# Example: Increase replicas or resources for production
# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/replicas
#         value: 3
#     target:
#       kind: StatefulSet
#       name: kafka
