apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/management-api

images:
  - name: management-api:latest
    newName: docker.io/nimroddd/management-api
    newTag: 2d7160e97f0798f60ab4881745735de607ec7d20

# Example: Override resources for production
# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/resources/limits/memory
#         value: "512Mi"
#     target:
#       kind: Deployment
#       name: management-api
